management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wealth-atlas
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  datasource:
    url: ${spring.datasource.url}
    schema: auth
    username: auth_user
    password: secret

user:
  datasource:
    url: ${spring.datasource.url}
    schema: users
    username: users_user
    password: secret

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.atlas: DEBUG

jwt:
  secret: ${JWT_SECRET:default-secret-key}
  expiration: 3600

services:
  baseurl: http://localhost:8080
  auth:
    baseurl: ${services.baseurl}/auth
  user:
    baseurl: ${services.baseurl}/user
  investment:
    baseurl: ${services.baseurl}/investment
  loan:
    baseurl: ${services.baseurl}/loan